###############################################################################
#                         docker-compose up --build -d                        #
###############################################################################

version: '3.1'
services:
  mysql:
    container_name: php-mysql
    image: 'mysql:8.0'
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '54002:3306'
    restart: unless-stopped

  webserver:
    container_name: php-server
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - './public:/application/public'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php-fpm
    ports:
      - '54000:80'
    restart: unless-stopped

  php-fpm:
    container_name: php-form
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    volumes:
      - './App:/application/App'
      - './public:/application/public'
      - './config:/application/config'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-my-admin
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - '54003:80'
    restart: unless-stopped

volumes:
  mysql_data: